@startuml class

package Util {
  class Request {
    #request: {}
    +get(url)
  }
}

package Client {
  

  interface IInfoPraia {
    alturaOnda
    direçãoOnda
    alturaOndulação
    direçãoOndulação
    períodoOndulação
    Velocidade do Vento
    Direção do Vento 
  }

  class ApiInfoPraia {
    alturaOnda
    direçãoOnda
    alturaOndulação
    direçãoOndulação
    períodoOndulação
    Velocidade do Vento
    Direção do Vento
  }
}
package Models {

  interface IUser {
    -id: String
    -name: String
    -email: String
    -password: String
  }

  interface ModelUser extends IUser {
    
  }

  enum Position {
    N
    S
    L
    O
  }

  interface IPraia {
    -id: Integer
    -name: String
    -position[1]: Position
    -lat: Integer
    -lng: Integer
    -user: String
  }

  IPraia -> Position

  interface PraiaModel extends IPraia

  class Praia implements PraiaModel
}
package Controllers {}
package Middlewares {}
package Services {}

@enduml