@startuml class

package Client {
  class ApiInfoPraia {
    Altura da onda
    Direção da onda
    Altura da ondulação
    Direção do ondulação
    Período de ondulação
    Velocidade do vento
    Direção do vento 
  }
}
package Controllers {}
package Middlewares {}
package Models {}
package Services {}
package Cliente {}
package Cliente {}
package Cliente {}
package Cliente {}

@enduml