@startuml class

package Util {
  class Request {
    #request: {}
    +get(url)
  }
}

package Client {
  
  interface IInfoPraiaData {
    [key: String]: number
  }

  interface IInfoPraia {
    alturaOnda: IinfoPraiaData
    direçãoOnda: IinfoPraiaData
    alturaOndulação: IinfoPraiaData
    direçãoOndulação: IinfoPraiaData
    períodoOndulação: IinfoPraiaData
    velocidadeVento: IinfoPraiaData
    direçãoVento: IinfoPraiaData
  }

  interface IPrevisãoPonto {
    alturaOnda: In
    direçãoOnda: In
    alturaOndulação: In
    direçãoOndulação: In
    períodoOndulação: In
    velocidadeVento: In
    direçãoVento: In
  }

  class ApiInfoPraia {
    alturaOnda
    direçãoOnda
    alturaOndulação
    direçãoOndulação
    períodoOndulação
    velocidadeVento
    direçãoVento
  }
}
package Models {

  interface IUser {
    -id: String
    -name: String
    -email: String
    -password: String
  }

  interface ModelUser extends IUser {
    
  }

  enum Position {
    N
    S
    L
    O
  }

  interface IPraia {
    -id: Integer
    -name: String
    -position[1]: Position
    -lat: Integer
    -lng: Integer
    -user: String
  }

  IPraia -> Position

  interface PraiaModel extends IPraia

  class Praia implements PraiaModel
}
package Controllers {}
package Middlewares {}
package Services {}

@enduml