@startuml class
class ApiInfoPraia {
  Altura da onda
  Direção da onda
  Período de onda
  Altura da ondulação
  Direção do swell
  Período de Swell
  Swell Secundário
  Altura da onda do vento
  Direção das ondas do vento
  Período de Ondas de Vento
  Temperatura da água
  Cobertura de gelo 
}
@enduml